sudo: required

branches:
  only:
  - master

env:
  global:
    - DOCKER_REPO=getsentry/rust-musl-cross
    ### Encrypted via https://docs.travis-ci.com/user/encryption-keys/#usage
    # DOCKER_USER
    - secure: "kvFK+6zTFyIUVipmaUKKFBKqd7YEAS8OI3BslAa04PpgX2V2ssbxEMojEoWOXhHV108JAqkSgeOFvTQl9hOCzTT6USEDm14jVr8hoHElyGK49WAnR1EVaHunt16i4AeSJj9vjdO2iQ35rQiWfNBD6gp8Wv4lcNv2mgMgvkwmrUYt933JKDPsSUUKKKSgFAMmhXcTu5vVncSAZhALPzGkLP9BSdxiyammJcwWucG4VxUqP06y57inKIuDRS3eWqLlhctn51jzUBWFXO1Hu4ZIdBgIbswykAsVLi6w5qcKDRwJ7y2xfofrU9SeLScJgVZTzfzfNdVzJEHCRh6XCe2EqHTKF18wE6RjEQyjhbYl/lV8iMYRV6drZ+ezVZeWHpVAfxdN+qfoQWsOU7/qOR0T7AXKEAmXJVSujizD+BjKvDdvVXt0SbuvkewTgcxMC47E7YUehbimnIg6/YjUS+wgyZNlrK/3q5NVEu4ofHFN7z5v2WBEzdn/dWojPpME/RNHvwFlekahwYIBZiSo5IGcmsLnvz3g1fFbCHCbZojYCpV1RgKTzDQrm2yYqGkply01VekNPv2FPtjUBfNqSPI4mkt0Uf16/b19bHQh9fO/3vZtORY/SIgThvbcTERk69zRfR4N6C4tsdDoYxwgf1tVYRc7M12R0spagmCmL441IOY="
    # DOCKER_PASS
    - secure: "xCx9BOLWmHGwdd6xOAj4bzW5ciSMeYEmOjT9PfiSKWQiOrewmww+8LyeCbj+Hhso6n63fS+sDSZICkgtYOmOsFUpXt05/fBCXcpUcWgPsQr4IAwxIxvZudF6CsMIjYET89aqD2ohf5QsilK2ErPIJWYQ0LybvIhlbNgo8Q0et+zXEt5UNmS6asLcKVp1geLZsqMfz050hNWclKXlhBlr9Wnmvd/3GoTjN2BayD+QZT1w8D5UU1HAAiqqa3BaXJH0WpEkpDJt2XHSMsbSde5ShSspU9hqnhKqu6crr42sPexPGugsYQN7PJMyTPBKi544AerUAJEztiIh3eRTq6My81P/gO1rNJnbL9D7apGN3xXLQ88/vZdZQWhKNsfTk0VfllZu8EPqKnAx9uWnM4fd0x0F6fHCL9rBFLNb9HXqr0xmo4qou2ajln4rgDH0R5F8XFJm5HPDJu8qiDUVXIU75V8utlvI1ue44Qfi0bUzxsLoZ3uOftCITlNtJWuKCJKQf33WshhIhO1H2vBR0npJq7DenlgYoKnY+iXdg7aoos3OI4yGexujkAvrjnfvqTwyKg0DhTex+hj12IBS5foeGbNL179zTNW9PiN9ogXG5cDWWr5+zUei7lzfWpFj2/G8278jmtXaMkV9QjI8rDcKgurmbCkKxY8dxokUUe5Lg78="

matrix:
  include:
    - env: IMAGE_TAG=x86_64-musl TARGET=x86_64-unknown-linux-musl OPENSSL_ARCH=linux-x86_64
#    - env: IMAGE_TAG=arm-musleabi TARGET=arm-unknown-linux-musleabi OPENSSL_ARCH=linux-generic32
#    - env: IMAGE_TAG=arm-musleabihf TARGET=arm-unknown-linux-musleabihf OPENSSL_ARCH=linux-generic32
#    - env: IMAGE_TAG=armv7-musleabihf TARGET=armv7-unknown-linux-musleabihf OPENSSL_ARCH=linux-generic32
    - env: IMAGE_TAG=i686-musl TARGET=i686-unknown-linux-musl OPENSSL_ARCH=linux-generic32
#    - env: IMAGE_TAG=mips-musl TARGET=mips-unknown-linux-musl OPENSSL_ARCH=linux-mips32
#    - env: IMAGE_TAG=mipsel-musl TARGET=mipsel-unknown-linux-musl OPENSSL_ARCH=linux-mips32

script:
  - echo "Building Docker image for target ${TARGET}"
  - docker build --build-arg TARGET="$TARGET" --build-arg OPENSSL_ARCH="$OPENSSL_ARCH" -t $DOCKER_REPO:$IMAGE_TAG .
  - docker run --rm -it -v "$(pwd)/tests":/home/rust/src $DOCKER_REPO:$IMAGE_TAG cargo build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      PERSISTENT_TAG="${IMAGE_TAG}-$(date +'%Y%m%d-%H%M%S')"
      docker tag "${DOCKER_REPO}:${IMAGE_TAG}" "${DOCKER_REPO}:${PERSISTENT_TAG}"

      docker push "${DOCKER_REPO}:${IMAGE_TAG}"
      docker push "${DOCKER_REPO}:${PERSISTENT_TAG}"
    fi
